version: '3.7'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - 3306:3306
    volumes:
     - "./init.sql:/docker-entrypoint-initdb.d/1.sql"